'use strict';
const fs   = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { SAFE_ENV }  = require('../middleware/security');
const templates     = require('./templates.service');

function botsRoot() { return path.resolve(process.env.BOTS_ROOT || '/opt'); }
function botPath(name) { return path.join(botsRoot(), name); }

// ── Bot creation ───────────────────────────────────────────
async function createBot({ name, token, templateId = 'discordjs-blank', extraPackages = [], envVars = {}, language = 'en' }) {
  const dir = botPath(name);
  if (fs.existsSync(dir)) throw new Error(`Le dossier /opt/${name} existe déjà.`);

  fs.mkdirSync(dir, { recursive: true });

  // Generate files from template (passing language so the template can
  // localize the user-facing strings it embeds).
  let files;
  try {
    files = templates.generateFiles(templateId, { language });
  } catch (e) {
    // Fallback to minimal bot
    files = { 'index.js': `require('dotenv').config();\nconst { Client, GatewayIntentBits } = require('discord.js');\nconst client = new Client({ intents: [GatewayIntentBits.Guilds] });\nclient.once('ready', () => console.log('✅ Connecté'));\nprocess.on('unhandledRejection', console.error);\nclient.login(process.env.TOKEN);\n` };
  }

  // Write template files
  for (const [fname, content] of Object.entries(files)) {
    const fpath = path.join(dir, fname);
    fs.mkdirSync(path.dirname(fpath), { recursive: true });
    fs.writeFileSync(fpath, content, 'utf8');
  }

  // Write .env — always include TOKEN + any custom vars
  const tpl = templates.getTemplate(templateId);
  let envContent = `# Bot: ${name}\n# Generated by Nexus Bot Manager\n\nTOKEN=${token || ''}\n`;
  if (tpl) {
    for (const ev of tpl.envVars || []) {
      if (ev.key === 'TOKEN') continue;
      const val = envVars[ev.key] || '';
      envContent += `${ev.key}=${val}\n`;
    }
  }
  fs.writeFileSync(path.join(dir, '.env'), envContent);

  // package.json
  const pkgJson = {
    name, version: '1.0.0', main: 'index.js',
    scripts: { start: 'node index.js' },
    description: `Discord bot managed by Nexus Bot Manager`
  };
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify(pkgJson, null, 2));

  // .gitignore
  fs.writeFileSync(path.join(dir, '.gitignore'), 'node_modules/\n.env\n*.log\ndata/\n');

  // README
  fs.writeFileSync(path.join(dir, 'README.md'),
    `# ${name}\n\nBot Discord géré par [Nexus Bot Manager](https://github.com/Julien48003/nexus-bot-manager).\n\n` +
    `- Template: ${templateId}\n- Créé le: ${new Date().toLocaleDateString('fr-FR')}\n\n` +
    `## Démarrage\n\`\`\`bash\nnode index.js\n\`\`\`\n`);

  // npm install
  const tplPkgs = (tpl && tpl.packages) || ['discord.js', 'dotenv'];
  const allPkgs = [...new Set([...tplPkgs, ...extraPackages.filter(p => /^[a-zA-Z0-9@/_.-]+$/.test(p))])];

  try {
    execFileSync('npm', ['install', ...allPkgs, '--save', '--loglevel=warn'], {
      cwd: dir, timeout: 120000, env: SAFE_ENV, stdio: 'pipe', shell: false
    });
  } catch (e) {
    console.warn(`[fs] npm install warning for ${name}:`, e.message?.split('\n')[0]);
    // Non-fatal — bot created, user can install deps manually
  }

  return dir;
}

function deleteBot(name) {
  const dir = botPath(name);
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
}

// ── File tree (recursive, excludes node_modules) ──────────
function listDirectory(dirPath, depth = 0, maxDepth = 6) {
  if (depth > maxDepth) return [];
  const items = [];
  try {
    for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
      if (entry.name === 'node_modules') continue;
      if (entry.name.startsWith('.') && !['env', 'gitignore'].some(n => entry.name.endsWith(n))) continue;

      const full = path.join(dirPath, entry.name);
      if (entry.isDirectory()) {
        items.push({ name: entry.name, type: 'dir', path: full, children: listDirectory(full, depth + 1, maxDepth) });
      } else {
        let size = 0;
        try { size = fs.statSync(full).size; } catch (_) {}
        items.push({ name: entry.name, type: 'file', path: full, size });
      }
    }
  } catch (_) {}

  return items.sort((a, b) => {
    if (a.type !== b.type) return a.type === 'dir' ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
}

function readFile(fp)           { return fs.readFileSync(fp, 'utf8'); }
function writeFile(fp, content) { fs.mkdirSync(path.dirname(fp), { recursive: true }); fs.writeFileSync(fp, content, 'utf8'); }
function deleteFile(fp)         { fs.unlinkSync(fp); }
function renameFile(old, nw)    { fs.renameSync(old, nw); }
function createDir(dp)          { fs.mkdirSync(dp, { recursive: true }); }

module.exports = { createBot, deleteBot, listDirectory, readFile, writeFile, deleteFile, renameFile, createDir, botPath, botsRoot };
